//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppendixD
    {
        public int ID { get; set; }
        public Nullable<int> ContractUniqueID { get; set; }
        public byte[] AppendixD_Attachment { get; set; }
        public string Conttype { get; set; }
    }
}
