//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_04_05
    {
        public int ID { get; set; }
        public string Language { get; set; }
        public string Rev { get; set; }
        public Nullable<System.DateTime> Revdate { get; set; }
        public string QualityCode { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> ContractDay { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ContractValuenumber { get; set; }
        public Nullable<System.DateTime> ContractValueText { get; set; }
        public string Secondparty_Address { get; set; }
        public string Secondparty_AuthpersSign { get; set; }
        public string Secondparty_Compname { get; set; }
        public string Secondparty_Representative { get; set; }
        public string Secondparty_Tele { get; set; }
        public string Secondparty_Fax { get; set; }
        public string Secondparty_Email { get; set; }
        public string SiteAddress { get; set; }
        public string Concreteprice { get; set; }
        public string ApprovalDocumentValue { get; set; }
        public string ApprovalDocumenttext { get; set; }
        public string ApprovalDocumentDurationbyday { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
    }
}
