//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_01_E15
    {
        public int ID { get; set; }
        public string Language { get; set; }
        public string Rev { get; set; }
        public Nullable<System.DateTime> Revdate { get; set; }
        public string QualityCode { get; set; }
        public Nullable<System.DateTime> Secondparty_Compname_En { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ContractDay_En { get; set; }
        public Nullable<System.DateTime> ContractDate_En { get; set; }
        public Nullable<System.DateTime> Secondparty_Address_En { get; set; }
        public Nullable<System.DateTime> Secondparty_Tele_En { get; set; }
        public Nullable<System.DateTime> Secondparty_Fax_En { get; set; }
        public Nullable<System.DateTime> Secondparty_Email_En { get; set; }
        public Nullable<System.DateTime> Secondparty_AuthpersSign_En { get; set; }
        public Nullable<System.DateTime> Secondparty_Representative_En { get; set; }
        public Nullable<System.DateTime> MainClient_En { get; set; }
        public Nullable<System.DateTime> Scopeofworks_En { get; set; }
        public Nullable<System.DateTime> StateNameSecondPartyCompany { get; set; }
        public Nullable<System.DateTime> SERVICEOFPREBIDAGREEMENT { get; set; }
        public Nullable<System.DateTime> TenderNo { get; set; }
        public Nullable<System.DateTime> TenderName { get; set; }
        public Nullable<System.DateTime> TypeofAgreement { get; set; }
        public Nullable<System.DateTime> NameofAgreement { get; set; }
        public Nullable<System.DateTime> ServicesName { get; set; }
        public Nullable<System.DateTime> DocumentReferenceNumber { get; set; }
        public Nullable<System.DateTime> degreeofaccuracy { get; set; }
        public Nullable<System.DateTime> specifiedTenderDocuments { get; set; }
        public Nullable<System.DateTime> accuracyofquantities { get; set; }
        public Nullable<System.DateTime> Subcontractorliabilities { get; set; }
        public Nullable<System.DateTime> FeesDetails { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
    }
}
