//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracttype
    {
        public int ID { get; set; }
        public string Contname { get; set; }
        public string ContType { get; set; }
        public string Lang { get; set; }
        public string QualityCode { get; set; }
        public Nullable<System.DateTime> RevDate { get; set; }
        public string Notes { get; set; }
        public string Revno { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
