//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_01_L12
    {
        public int ID { get; set; }
        public string Language { get; set; }
        public string Rev { get; set; }
        public Nullable<System.DateTime> Revdate { get; set; }
        public string QualityCode { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractDay { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ContractValuenumber { get; set; }
        public string ContractValueText { get; set; }
        public string ProjectName { get; set; }
        public string LoadMaterialFactory { get; set; }
        public string LoadMaterialFactoryArea { get; set; }
        public string LoadMaterialFactoryCountry { get; set; }
        public string DeliveryMaterialFactory { get; set; }
        public string OtherExpenses { get; set; }
        public string Countryofshipmentdamage { get; set; }
        public string Secondparty_Address { get; set; }
        public string Secondparty_AuthpersSign { get; set; }
        public string Secondparty_Compname { get; set; }
        public string Secondparty_Representative { get; set; }
        public string Secondparty_Tele { get; set; }
        public string Secondparty_Email { get; set; }
        public string Secondparty_Fax { get; set; }
        public string ProjectName_En { get; set; }
        public Nullable<System.DateTime> ContractDate_En { get; set; }
        public string ContractDay_En { get; set; }
        public string ContractValuenumber_En { get; set; }
        public string ContractValueText_En { get; set; }
        public string LoadMaterialFactory_En { get; set; }
        public string LoadMaterialFactoryArea_En { get; set; }
        public string LoadMaterialFactoryCountry_En { get; set; }
        public string DeliveryMaterialFactory_En { get; set; }
        public string OtherExpenses_En { get; set; }
        public string Countryofshipmentdamage_En { get; set; }
        public string Secondparty_Address_En { get; set; }
        public string Secondparty_AuthpersSign_En { get; set; }
        public string Secondparty_Compname_En { get; set; }
        public string Secondparty_Representative_En { get; set; }
        public string Secondparty_Tele_En { get; set; }
        public string Secondparty_Email_En { get; set; }
        public string Secondparty_Fax_En { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
    
        public virtual Contracttype Contracttype { get; set; }
        public virtual LMS_User LMS_User { get; set; }
    }
}
