//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_01_E15
    {
        public int ID { get; set; }
        public string Language { get; set; }
        public string Rev { get; set; }
        public Nullable<System.DateTime> Revdate { get; set; }
        public string QualityCode { get; set; }
        public string Secondparty_Compname_En { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ContractDay_En { get; set; }
        public Nullable<System.DateTime> ContractDate_En { get; set; }
        public string Secondparty_Address_En { get; set; }
        public string Secondparty_Tele_En { get; set; }
        public string Secondparty_Fax_En { get; set; }
        public string Secondparty_Email_En { get; set; }
        public string Secondparty_AuthpersSign_En { get; set; }
        public string Secondparty_Representative_En { get; set; }
        public string MainClient_En { get; set; }
        public string Scopeofworks_En { get; set; }
        public string StateNameSecondPartyCompany { get; set; }
        public string SERVICEOFPREBIDAGREEMENT { get; set; }
        public string TenderNo { get; set; }
        public string TenderName { get; set; }
        public string TypeofAgreement { get; set; }
        public string NameofAgreement { get; set; }
        public string ServicesName { get; set; }
        public string DocumentReferenceNumber { get; set; }
        public string degreeofaccuracy { get; set; }
        public string specifiedTenderDocuments { get; set; }
        public string accuracyofquantities { get; set; }
        public string Subcontractorliabilities { get; set; }
        public string FeesDetails { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
    
        public virtual Contracttype Contracttype { get; set; }
        public virtual LMS_User LMS_User { get; set; }
    }
}
