//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class eMedical_BookingTiming
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string BookingTimeBegin { get; set; }
        public string BookingTimeEnd { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<int> TimingSerial { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual eMedical_Service eMedical_Service { get; set; }
        public virtual eMedical_User eMedical_User { get; set; }
        public virtual eMedical_Room eMedical_Room { get; set; }
    }
}
