//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_User
    {
        public int ID { get; set; }
        public Nullable<int> PersonnelID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> ReportingTo { get; set; }
        public string Qualification { get; set; }
        public string Major { get; set; }
        public string University { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string ProfilePicPath { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual LMS_Roles LMS_Roles { get; set; }
    }
}
