//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_HRRolesList
    {
        public int ID { get; set; }
        public Nullable<int> PersonnelID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> MobDate { get; set; }
        public Nullable<System.DateTime> DemobDate { get; set; }
    
        public virtual u_HRRoles u_HRRoles { get; set; }
    }
}
