//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_HRGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public u_HRGroup()
        {
            this.u_HRRoles = new HashSet<u_HRRoles>();
        }
    
        public int ID { get; set; }
        public string Group { get; set; }
        public Nullable<int> HeadingOrder { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> Root { get; set; }
        public string SubGroup { get; set; }
        public string SectionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_HRRoles> u_HRRoles { get; set; }
    }
}
