//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_HRRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public u_HRRoles()
        {
            this.u_HRPersonnel = new HashSet<u_HRPersonnel>();
            this.u_HRRolesList = new HashSet<u_HRRolesList>();
        }
    
        public int RoleID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string PositionCode { get; set; }
        public string ClassCode { get; set; }
        public Nullable<int> HeadingOrder { get; set; }
        public string Grade { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_HRPersonnel> u_HRPersonnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_HRRolesList> u_HRRolesList { get; set; }
    }
}
