//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_eMedical_RolesCount
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> CountUsers { get; set; }
        public Nullable<int> UsableBy { get; set; }
    }
}
