//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GroupsPersonnel
    {
        public int ID { get; set; }
        public string Group { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ParentGroup { get; set; }
        public Nullable<int> HeadingOrder { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int RoleID { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public Nullable<int> PersonnelID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Status { get; set; }
        public string FName { get; set; }
    }
}
