//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RoleGroups
    {
        public int RoleID { get; set; }
        public string Group { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountPersonnel { get; set; }
    }
}
