//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBookingAppointment
    {
        public int BTID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string TimeBegins { get; set; }
        public string TimeEnds { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> BookingDate_TimeBegin { get; set; }
        public Nullable<System.DateTime> BookingDate_TimeEnd { get; set; }
        public string RoomName { get; set; }
        public string ServiceName { get; set; }
        public string FName { get; set; }
    }
}
