//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHREmployee
    {
        public int ID { get; set; }
        public string FileNo { get; set; }
        public string EmpId { get; set; }
        public string FullnameAr { get; set; }
        public string FullnameEn { get; set; }
        public string Designation { get; set; }
        public string Nationality { get; set; }
        public string CivilId { get; set; }
        public string ResidencyDate { get; set; }
        public string PassportNo { get; set; }
        public string PassportExpDate { get; set; }
        public string Status { get; set; }
        public string JoinedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AddedBy { get; set; }
        public string TransferedFrom { get; set; }
        public string TransferedFromDate { get; set; }
        public string Salary { get; set; }
        public string TransferedTo { get; set; }
        public string TransferedToDate { get; set; }
        public bool RTD { get; set; }
        public string VacationFrom { get; set; }
        public string VacationTo { get; set; }
        public string VacationFromDays { get; set; }
        public string VacationExt_1_From { get; set; }
        public string VacationExt_1_To { get; set; }
        public string VacationExt_2_From { get; set; }
        public string VacationExt_2_To { get; set; }
        public string VacationExt_3_From { get; set; }
        public string VacationExt_3_To { get; set; }
    }
}
