//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vService
    {
        public string HospitalName { get; set; }
        public string Clinicname { get; set; }
        public string FName { get; set; }
        public string FirstName { get; set; }
        public string EmployeeNo { get; set; }
        public string Email { get; set; }
        public int SID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> NoofSessions { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public string ServiceType { get; set; }
        public string ShownFor { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string RoomName { get; set; }
    }
}
